table
mate-academy/py-genres-and-actors pull request #179
Opened 2022-12-08 20:30 UTC by bythewaters

2022-12-09 15:32 UTC, YuriiKindrat requested changes

2022-12-09 15:32 UTC, YuriiKindrat commented on main.py
> +                  "Scarlett Johansson"]:
it'll be better if u create the separate variable for actors

2022-12-10 09:50 UTC, OleksandrPozden requested changes

2022-12-10 09:50 UTC, OleksandrPozden commented on main.py
> +              "Scarlett Johansson"]
```suggestion
    actors = [
          "George Klooney",
           "Kianu Reaves",
           "Will Smith",
           "Jaden Smith",
           "Scarlett Johansson"
       ]
```

2022-12-10 12:51 UTC, OleksandrPozden approved these changes

2024-06-10 16:56 UTC, closed without merging