Initial implementation
mate-academy/py-genres-and-actors pull request #394
Opened 2023-06-26 07:23 UTC by thorium-zero

2023-06-27 15:02 UTC, oleksiikolii approved these changes
I'm not sure you need to add .gitignore but code looks good

2023-07-03 10:48 UTC, LiudmylaKulinchenko approved these changes
Well done 🐇🍬

2023-07-03 10:57 UTC, LiudmylaKulinchenko requested changes

2023-07-03 10:57 UTC, LiudmylaKulinchenko commented on main.py
> +    Actor.objects.bulk_create([
You can skip creating the intermediate lists and directly pass the generator expressions to the bulk_create() method

2023-07-11 12:44 UTC, Oleg-s-s approved these changes
:+1:

2023-07-27 10:34 UTC, closed without merging