Solution #1
mate-academy/py-genres-and-actors pull request #401
Opened 2023-06-28 12:02 UTC by erikagayan

2023-07-02 14:13 UTC, Tarasidze requested changes
You need to add migrations to your pull request. You may use: "git add PATH_TO _YOUR_FILE" command or change .gitignore file.
Everything else is ok!

2023-07-03 10:12 UTC, LiudmylaKulinchenko requested changes
tests didn't pass

2023-07-03 13:31 UTC, Oleg-s-s requested changes
Taras mentioned that you need migrations on a pr. Thats true but holding db itself on git is a crucial mistake. remove db from your pr

2023-07-03 13:31 UTC, Oleg-s-s commented on main.py
> +        )
move variables to top and then apply some operations. That will make your code easier to understand

2023-07-03 14:55 UTC, Oleg-s-s requested changes
You still left your db in pr, it should be removed

2023-08-10 15:50 UTC, closed without merging