Solution
mate-academy/py-genres-and-actors pull request #466
Opened 2023-08-23 14:10 UTC by ip-ilya

2023-08-23 14:28 UTC, Polyakiv-Andrey requested changes
Tests not passed

2023-08-24 11:01 UTC, ArsenPidhoretskyi requested changes

2023-08-24 11:01 UTC, ArsenPidhoretskyi commented on main.py
> +        first_name, last_name = actor_str.split()[0], actor_str.split()[1]
```suggestion
        first_name, last_name = actor_str.split()
```
No need to split two times

2023-08-28 10:04 UTC, ArsenPidhoretskyi approved these changes
Well done!

2023-08-28 10:14 UTC, Bohdan-Salamakha approved these changes

2024-08-01 15:03 UTC, closed without merging