solution
mate-academy/py-genres-and-actors pull request #648
Opened 2024-01-14 14:15 UTC by uzlss

Please, check everything! I have not been studying for 2 months! I FEEL VeRy wrong! thank you <3

2024-01-14 17:14 UTC, vsmutok requested changes

2024-01-14 17:14 UTC, vsmutok commented on main.py
> +    return Actor.objects.all().filter(last_name="Smith").order_by("first_name")
```suggestion
    return Actor.objects.filter(last_name="Smith").order_by("first_name")
```

2024-01-14 17:33 UTC, vsmutok requested changes

2024-01-14 17:33 UTC, vsmutok commented on main.py
> +    return Actor.objects.all().filter(last_name="Smith").order_by("first_name")
```suggestion
    return Actor.objects.filter(last_name="Smith").order_by("first_name")
```

2024-01-15 13:40 UTC, vasylhnatiuk approved these changes

2024-04-23 03:23 UTC, closed without merging